version: '2'

services:
  web-server:
    build: .
    ports:
      - 80:8000
    links:
      - db
    networks:
      - laravel-network

  db:
    image: postgres:9.6.2
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=laravel
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
