version: '2'

services:
  web-server:
    build: ops/web-server
    ports:
      - 80:8000
    volumes:
      - ./app:/app
    working_dir: /app
    links:
      - db
    networks:
      - laravel-network
    command: make run

  frontend:
    image: node:latest
    command: make watch
    working_dir: /src
    volumes:
      - ./frontend:/src
      - ./app:/app
      - /src/node_modules

  db:
    image: postgres:9.6.2
    environment:
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=laravel
      - POSTGRES_DB=laravel
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
